inc_file_path: "/tmp/vagrant-puppet/files" # Absolute path to the puppet template files directory (No need to change it)
tz: "America/Sao_Paulo" # Timezone
user: "vagrant" # User to create
password: "vagrant" # The user's password
project: "PROJECT" # Django project folder or the name when you run django-admin.py startproject <PROJECT_NAME>
domain_name: "localhost" # Used in nginx, uwsgi and virtualenv directory
db_name: "PROJECT" # PostgreSQL database name to create
db_user: "PROJECT" # PostgreSQL username to create
db_password: "PROJECT" # PostgreSQL password for user
